//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientSetting
    {
        public int ClientSettingsID { get; set; }
        public System.Guid ClientID { get; set; }
        public string ClientName { get; set; }
        public string FileSharePath { get; set; }
        public string FileShareUserName { get; set; }
        public string FileSharePassword { get; set; }
    }
}
