//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicReportHistoryType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DynamicReportHistoryType()
        {
            this.DynamicReportHistories = new HashSet<DynamicReportHistory>();
        }
    
        public int DynamicReportHistoryTypeID { get; set; }
        public string HistoryType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DynamicReportHistory> DynamicReportHistories { get; set; }
    }
}
