//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicReportHistoryDetail
    {
        public int DynamicReportHistoryDetailID { get; set; }
        public int DynamicReportHistoryID { get; set; }
        public int DynamicReportHistoryDetailTypeID { get; set; }
        public string DynamicReportHistoryDetail1 { get; set; }
    
        public virtual DynamicReportHistory DynamicReportHistory { get; set; }
    }
}
