//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicReportMetric
    {
        public int DynamicReportMetricID { get; set; }
        public System.Guid DynamicReportGUID { get; set; }
        public int DynamicReportMetricTypeID { get; set; }
        public int DynamicReportServerID { get; set; }
        public int ApplicationID { get; set; }
        public int DynamicReportRenderFormatID { get; set; }
        public string UserName { get; set; }
        public string ClientName { get; set; }
        public System.DateTime StartMetricDateTime { get; set; }
        public System.DateTime EndMetricDateTime { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    }
}
