//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicReportHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DynamicReportHistory()
        {
            this.DynamicReportHistoryDetails = new HashSet<DynamicReportHistoryDetail>();
        }
    
        public int DynamicReportHistoryID { get; set; }
        public System.Guid DynamicReportGUID { get; set; }
        public System.Guid HistoryGroupGUID { get; set; }
        public int DynamicReportHistoryTypeID { get; set; }
        public string History { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    
        public virtual DynamicReportHistoryType DynamicReportHistoryType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DynamicReportHistoryDetail> DynamicReportHistoryDetails { get; set; }
    }
}
