//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DynamicReport()
        {
            this.DynamicReportParameters = new HashSet<DynamicReportParameter>();
            this.SubscriptionInfoes = new HashSet<SubscriptionInfo>();
        }
    
        public int DynamicReportID { get; set; }
        public System.Guid DynamicReportGUID { get; set; }
        public Nullable<System.Guid> ResourceID { get; set; }
        public int DynamicReportTypeID { get; set; }
        public int DynamicReportServerID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string SSRSPath { get; set; }
        public bool HasDataSource { get; set; }
        public bool HasParameters { get; set; }
        public bool AllowExcelExport { get; set; }
        public bool AllowWordExport { get; set; }
        public bool AllowPDFExport { get; set; }
        public bool ReadyForOnDemandGeneration { get; set; }
        public bool ReadyForSubscriptionGeneration { get; set; }
        public string DataDrivenDataSourceConnectionString { get; set; }
        public string DataDrivenDataSourceUserName { get; set; }
        public string DataDrivenDataSourcePassword { get; set; }
        public string DataDrivenRecipientAndFieldSQL { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual DynamicReportServer DynamicReportServer { get; set; }
        public virtual DynamicReportType DynamicReportType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DynamicReportParameter> DynamicReportParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionInfo> SubscriptionInfoes { get; set; }
    }
}
