//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicReportParameter
    {
        public int DynamicReportParameterID { get; set; }
        public int DynamicReportID { get; set; }
        public string Name { get; set; }
        public string ParameterType { get; set; }
        public bool Nullable { get; set; }
        public bool NullableSpecified { get; set; }
        public bool AllowBlank { get; set; }
        public bool AllowBlankSpecified { get; set; }
        public bool MultiValue { get; set; }
        public bool MultiValueSpecified { get; set; }
        public bool QueryParameter { get; set; }
        public bool QueryParameterSpecified { get; set; }
        public Nullable<int> MinLength { get; set; }
        public Nullable<int> MaxLength { get; set; }
        public string MinValue { get; set; }
        public string MaxValue { get; set; }
        public string RegularExpressionValidation { get; set; }
        public string UIControlType { get; set; }
        public Nullable<int> UIRow { get; set; }
        public Nullable<int> UIColumn { get; set; }
        public string ClaimTypeName { get; set; }
    
        public virtual DynamicReport DynamicReport { get; set; }
        public virtual ParameterType ParameterType1 { get; set; }
    }
}
