//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionClientData
    {
        public int SubscriptionClientDataID { get; set; }
        public System.Guid SubscriptionID { get; set; }
        public System.Guid ClientID { get; set; }
        public string ReciepientEMailAddress { get; set; }
        public string Contract { get; set; }
        public Nullable<int> SalesYear { get; set; }
        public Nullable<int> CompositeGroupID { get; set; }
        public Nullable<System.DateTime> DRDateTime { get; set; }
        public Nullable<bool> DRBoolean { get; set; }
    
        public virtual SubscriptionClientData SubscriptionClientData1 { get; set; }
        public virtual SubscriptionClientData SubscriptionClientData2 { get; set; }
    }
}
