//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionInfo
    {
        public int SubscriptionInfoID { get; set; }
        public int DynamicReportID { get; set; }
        public System.Guid DynamicReportGUID { get; set; }
        public System.Guid SubscriptionID { get; set; }
        public System.Guid ClientID { get; set; }
        public string DeliveryType { get; set; }
        public string EventType { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public string FileExtension { get; set; }
        public string RenderFormat { get; set; }
        public string WriteMode { get; set; }
        public string EMailFrom { get; set; }
        public string EMailTo { get; set; }
        public string EMailCC { get; set; }
        public string EMailBcc { get; set; }
        public string EMailReplyTo { get; set; }
        public string EMailSubject { get; set; }
        public Nullable<bool> EMailIncludeReport { get; set; }
        public Nullable<bool> EMailIncludeLink { get; set; }
        public Nullable<int> EMailPriorityID { get; set; }
        public string EMailComment { get; set; }
        public string ExtensionSettingsExtension { get; set; }
        public string ScheduleXML { get; set; }
        public Nullable<int> Timeout { get; set; }
        public Nullable<System.DateTime> LastRunDateTime { get; set; }
        public string LastRunStatus { get; set; }
    
        public virtual DynamicReport DynamicReport { get; set; }
    }
}
